version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "lior1206"  
      MYSQL_DATABASE: "picprodb"       
      MYSQL_USER: "lior"            
      MYSQL_PASSWORD: "lior1206"      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

