# Generated by Django 5.0.4 on 2024-06-02 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedphoto',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
