# Generated by Django 5.0.4 on 2024-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_page', '0002_uploadedphoto_uploaded_at_alter_uploadedphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
