# Generated by Django 5.0.4 on 2024-06-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading_page', '0003_alter_uploadedphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedphoto',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='uploadedphoto',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
